# Generated by Django 3.2.12 on 2022-03-02 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('avatarLink', models.CharField(max_length=400)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TopicElement',
            fields=[
                ('topicElementId', models.AutoField(primary_key=True, serialize=False)),
                ('topicTitle', models.CharField(max_length=100)),
                ('solvedTaskNum', models.PositiveIntegerField(default=0)),
                ('totalTaskNum', models.PositiveIntegerField(default=0)),
                ('ownBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.person')),
            ],
        ),
        migrations.CreateModel(
            name='TaskElement',
            fields=[
                ('taskElementId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField()),
                ('priority', models.CharField(choices=[('1', 'High'), ('2', 'Average'), ('3', 'Low'), ('4', 'None')], max_length=20)),
                ('isDone', models.BooleanField(default=False)),
                ('containedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.topicelement')),
            ],
        ),
    ]
